/**
 * Creates a unique ID for a component instance.
 *
 * @param prefix - component name prefix (e.g. "switch", "input", "checkbox")
 * @param uid - unique instance ID generated by $props.id()
 */
export function createId(prefix: string, uid: string): string {
  return `${prefix}-${uid}`;
}
